language: java
jdk:
- oraclejdk8
env:
- NODE_VERSION="7.4.0"
before_install:
- nvm install $NODE_VERSION
- node --version
install:
- npm install
script:
- npm run compile
- mvn package
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$TAGPERM@github.com/kits-ab/gakusei --tags
- ls -R
branches:
  except:
  - "/^*-v[0-9]/"

deploy:
  provider: releases
  api_key:
    secure: $TAGPERM
  file: target/gakusei-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: kits-ab/gakusei
    tags: false
    branch: develop
