language: java
jdk:
- oraclejdk8
before_install:
- if [[ `npm -v` != 4* ]]; then npm i -g npm@4.3.0; fi
install:
- npm install
script:
- npm run compile
- mvn package

# deploy to gakusei.daigaku.se via user ec2-user