branches:
  except:
  - "/^*-v[0-9]/"
  only:
  - develop

language: java
jdk:
- oraclejdk8
env:
- NODE_VERSION="7.4.0"
before_install:
- nvm install $NODE_VERSION
- node --version
install:
- npm install
script:
- npm run compile
- mvn package

after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push https://$TAGPERM@github.com/kits-ab/gakusei --tags

before_deploy:
- openssl aes-256-cbc -K $encrypted_3839e494e43c_key -iv $encrypted_3839e494e43c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: releases # put the release on github
    api_key:
      secure: "$TAGPERM"
    file: target/gakusei-0.0.1-SNAPSHOT.jar
    skip_cleanup: true
    on:
      repo: kits-ab/gakusei
      tags: true
  - provider: script # put the release on our live site
    skip_cleanup: true
    script: rsync --delete-after --quiet $TRAVIS_BUILD_DIR/target/gakusei-0.0.1-SNAPSHOT.jar ec2-user@gakusei.daigaku.se:home/ec2-user/gakusei-0.0.1-SNAPSHOT.jar.cool
    on:
      repo: kits-ab/gakusei
      # tags: true
cache:
  directories:
  - node_modules
  - $HOME/.m2
addons:
  ssh_known_hosts: gakusei.daigaku.se