branches:
  except:
  - "/^*-v[0-9]/"
  only:
  - master

language: java
jdk:
- oraclejdk8

script:
- mvn clean package -Pproduction

# the below will make each commit tagged. Skip this for now as we are not releasing to github releases currently
# after_success:
# - git config --global user.email "builds@travis-ci.com"
# - git config --global user.name "Travis CI"
# - export GIT_TAG=build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")
# - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
# - git push https://$TAGPERM@github.com/kits-ab/gakusei --tags

before_deploy:
- openssl aes-256-cbc -K $encrypted_3839e494e43c_key -iv $encrypted_3839e494e43c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  # 401 unauthorized, skip this for now ...
  # - provider: releases # put the release on github
  #   api_key:
  #     secure: "$TAGPERM"
  #   file: 
  #     - target/gakusei-1.0.7.jar
  #   skip_cleanup: true
  #   on:
  #     repo: kits-ab/gakusei
  #     all_branches: true
  - provider: script # put the release on our live site
    skip_cleanup: true
    script: scp $TRAVIS_BUILD_DIR/target/gakusei-1.0.6.jar ec2-user@gakusei.daigaku.se:gakusei.production.jar.to.deploy && ssh ec2-user@gakusei.daigaku.se sh Scripts/deploy_gakusei.sh
    on:
      repo: kits-ab/gakusei
      all_branches: true
      # tags: true
cache:
  directories:
  - node_modules
  - $HOME/.m2
addons:
  ssh_known_hosts: gakusei.daigaku.se
notifications:
  slack: kits:sGqgJPVSf7LU8x2am3PF6KQU