branches:
  except:
  - "/^*-v[0-9]/"
  only:
  - develop
  - master

language: java
jdk:
#- oraclejdk8
- oraclejdk10
env:
  global:
    - BABEL=true
    - NODE_VERSION="8.4.0"
    - KITS_SLACK=kits:sGqgJPVSf7LU8x2am3PF6KQU

before_install:
- nvm install $NODE_VERSION
- node --version
- git clone https://github.com/psandboge/japanese-grammar-utils.git
- cd japanese-grammar-utils && mvn install
- cd ..

install: true # Skip the default travis install phase

#before_script:

script:
# final build for deployment
- 'if [ "$TRAVIS_BRANCH" = "master" ]; then
    export DEPLOY_URL="production@gakusei.daigaku.se"
    export SLACK_PARAMETER=$KITS_SLACK
    export EMAIL_PARAMETER=true
    export FILENAME_SUFFIX="production";
  elif [ "$TRAVIS_BRANCH" = "develop" ]; then
    export DEPLOY_URL="staging@staging.daigaku.se"
    export SLACK_PARAMETER=false
    export EMAIL_PARAMETER=false
    export FILENAME_SUFFIX="staging";
  fi'
- mvn clean package -Pproduction
# integration testing
# - java -jar $TRAVIS_BUILD_DIR/target/gakusei.jar &
# - sleep 30
# - npm run test:saucelabs
# - pkill java


# Gives us the ssh key
before_deploy:
- openssl aes-256-cbc -K $encrypted_87c850735a16_key -iv $encrypted_87c850735a16_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script # put the release on our live site
    skip_cleanup: true
    script:
      - scp $TRAVIS_BUILD_DIR/target/gakusei.jar ${DEPLOY_URL}:gakusei.${FILENAME_SUFFIX}.jar.to.deploy && ssh ${DEPLOY_URL} sh Scripts/deploy_gakusei.sh
    on:
      repo: kits-ab/gakusei
      all_branches: true
      # tags: true
cache:
  directories:
  - node_modules
  - $HOME/.m2
addons:
  ssh_known_hosts:
    - gakusei.daigaku.se
    - staging.daigaku.se
  # sauce_connect: true
notifications:
  slack: $SLACK_PARAMETER
  email: $EMAIL_PARAMETER
