branches:
  except:
  - "/^*-v[0-9]/"
  only:
  - develop
  - master

language: java
jdk:
- oraclejdk8

script:
# integration testing
- mvn spring-boot:run -Pproduction &
- sleep 20
- BABEL_ENV=test ./node_modules/.bin/nightwatch --group play --config nightwatch.conf.sauce.js --env chrome
- pkill java
# final build for deployment
- if [ "$TRAVIS_BRANCH" = "master" ]; then export DEPLOY_URL="ec2-user@gakusei.daigaku.se" && export FILENAME_SUFFIX="production"; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then export DEPLOY_URL="ec2-user@staging.daigaku.se" && export FILENAME_SUFFIX="staging"; fi
- mvn clean package -Pproduction

# Gives us the ssh key
before_deploy:
- openssl aes-256-cbc -K $encrypted_3839e494e43c_key -iv $encrypted_3839e494e43c_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script # put the release on our live site
    skip_cleanup: true
    script: 
      - scp $TRAVIS_BUILD_DIR/target/gakusei.jar ${DEPLOY_URL}:gakusei.${FILENAME_SUFFIX}.jar.to.deploy && ssh ${DEPLOY_URL} sh Scripts/deploy_gakusei.sh
    on:
      repo: kits-ab/gakusei
      all_branches: true
      # tags: true
cache:
  directories:
  - node_modules
  - $HOME/.m2
addons:
  ssh_known_hosts:
    - gakusei.daigaku.se
    - staging.daigaku.se
  sauce_connect: true
notifications:
  slack: kits:sGqgJPVSf7LU8x2am3PF6KQU
